# Generated by Django 5.0 on 2023-12-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ish_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasib_nomi', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulot_nomi', models.CharField(max_length=250)),
                ('soni', models.CharField(max_length=250)),
                ('narxi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PraysIshchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_turi', models.CharField(max_length=250)),
                ('ish_narxi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PraysZakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_turi', models.CharField(max_length=250)),
                ('ish_narxi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Asilbek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('obyekt_nomi', models.CharField(max_length=250)),
                ('obyekt_fayli', models.FileField(upload_to='file')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('tel', models.IntegerField(max_length=250)),
                ('kelishilgan_summa', models.IntegerField(max_length=250)),
                ('olingan_summa', models.IntegerField(max_length=250)),
                ('bajarilgan_summa', models.IntegerField(max_length=250)),
                ('qoldiq', models.IntegerField(max_length=250)),
                ('ustavka', models.IntegerField(max_length=250)),
                ('tavsif', models.TextField()),
                ('status', models.CharField(choices=[('dg', 'danger'), ('pr', 'primary'), ('hs', 'history')], default='pr', max_length=2)),
                ('ish_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asilbek.ish_turi')),
                ('maxsulotlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asilbek.maxsulot')),
                ('prays_ishchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asilbek.praysishchi')),
                ('prays_zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asilbek.prayszakaz')),
            ],
            options={
                'ordering': ['ism'],
            },
        ),
    ]
