# Generated by Django 5.0 on 2023-12-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxsulot',
            name='narxi',
        ),
        migrations.RemoveField(
            model_name='maxsulot',
            name='soni',
        ),
        migrations.RemoveField(
            model_name='praysishchi',
            name='ish_narxi',
        ),
        migrations.RemoveField(
            model_name='prayszakaz',
            name='ish_narxi',
        ),
    ]
