# Generated by Django 5.0 on 2023-12-18 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0002_remove_maxsulot_narxi_remove_maxsulot_soni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asilbek',
            name='maxsulotlar',
        ),
        migrations.RemoveField(
            model_name='asilbek',
            name='prays_ishchi',
        ),
        migrations.RemoveField(
            model_name='asilbek',
            name='prays_zakaz',
        ),
        migrations.AlterModelOptions(
            name='asilbek',
            options={'ordering': ['-publish_time']},
        ),
        migrations.AlterField(
            model_name='asilbek',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Maxsulot',
        ),
        migrations.DeleteModel(
            name='PraysIshchi',
        ),
        migrations.DeleteModel(
            name='PraysZakaz',
        ),
    ]
