# Generated by Django 5.0 on 2023-12-18 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0003_remove_asilbek_maxsulotlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulot_nomi', models.CharField(max_length=250, unique=True)),
                ('soni', models.CharField(max_length=250)),
                ('narxi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PraysIshchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_turi', models.CharField(max_length=250, unique=True)),
                ('ish_nomi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PraysZakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_turi', models.CharField(max_length=250, unique=True)),
                ('ish_nomi', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ish_turi',
            new_name='Kasb_turi',
        ),
        migrations.CreateModel(
            name='Zakazlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('obyekt_nomi', models.CharField(max_length=250)),
                ('obyekt_fayli', models.FileField(upload_to='file')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('kelishilgan_summa', models.IntegerField(blank=True, null=True)),
                ('olingan_summa', models.IntegerField(blank=True, null=True)),
                ('bajarilgan_summa', models.IntegerField(blank=True, null=True)),
                ('qoldiq', models.IntegerField(blank=True, null=True)),
                ('ustavka', models.IntegerField(blank=True, null=True)),
                ('tavsif', models.TextField()),
                ('status', models.CharField(choices=[('dg', 'danger'), ('pr', 'primary'), ('hs', 'history')], default='pr', max_length=2)),
                ('ish_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asilbek.kasb_turi')),
                ('maxsulotlar', models.ForeignKey(default='-----', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='asilbek.maxsulot', to_field='maxsulot_nomi')),
                ('prays_ishchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asilbek.praysishchi', to_field='ish_turi')),
                ('prays_zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asilbek.prayszakaz', to_field='ish_turi')),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
        migrations.DeleteModel(
            name='Asilbek',
        ),
    ]
