# Generated by Django 5.0 on 2023-12-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0005_rename_ish_nomi_praysishchi_ish_narxi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kasb_turi',
            old_name='kasib_nomi',
            new_name='kasb_nomi',
        ),
    ]
