# Generated by Django 5.0 on 2023-12-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0006_rename_kasib_nomi_kasb_turi_kasb_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakazlar',
            name='login',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
