# Generated by Django 4.1.7 on 2023-12-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0008_alter_zakazlar_login_alter_zakazlar_tel_ishchilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('tel', models.CharField(default='', max_length=150)),
                ('manzil', models.CharField(max_length=250)),
                ('yosh', models.DateField(default='')),
                ('mutaxasislig', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='kasb_turi',
            name='kasb_nomi',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Ishchilar',
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='kasb',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='asilbek.kasb_turi', to_field='kasb_nomi'),
        ),
    ]
