# Generated by Django 4.1.7 on 2023-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0009_xodimlar_alter_kasb_turi_kasb_nomi_delete_ishchilar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etirozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('titul', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
