# Generated by Django 4.1.7 on 2023-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0011_etirozlar_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='oylik',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='zakazlar',
            name='obyekt_manzil',
            field=models.CharField(default='', max_length=250),
        ),
    ]
