# Generated by Django 4.1.7 on 2023-12-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0012_xodimlar_oylik_zakazlar_obyekt_manzil'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot',
            name='foiz',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='etirozlar',
            name='publish_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
