# Generated by Django 4.1.7 on 2023-12-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0013_maxsulot_foiz_alter_etirozlar_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot',
            name='foiz_narxi',
            field=models.CharField(default='', max_length=250),
        ),
    ]
