# Generated by Django 4.1.7 on 2023-12-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asilbek', '0014_maxsulot_foiz_narxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavdoTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulot_nomi', models.CharField(default='', max_length=250)),
                ('maxsulot_soni', models.CharField(default='', max_length=250)),
                ('maxsulot_narxi', models.CharField(default='', max_length=250)),
                ('save_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
